/**
 * Demo mode data - realistic repos based on actual popular GitHub repositories.
 * Stats are approximate snapshots to feel authentic without being stale.
 */

import type { Repository, User } from '../types';
import type { RadarWithCount, RadarRepo } from '../types/database';

// Demo user
export const DEMO_USER: User = {
  id: 'demo-user-id',
  login: 'demo-user',
  name: 'Demo User',
  avatar_url: '', // Empty to show generic person icon
  email: 'demo@example.com',
};

// Helper to generate a date within the last N days
function recentDate(daysAgo: number): string {
  const date = new Date();
  date.setDate(date.getDate() - daysAgo);
  return date.toISOString();
}

// Helper to generate starred_at dates spread over time
function starredDate(index: number): string {
  // Spread stars over the last 180 days
  const daysAgo = Math.floor((index / 45) * 180);
  return recentDate(daysAgo);
}

/**
 * 45 starred repos - real popular repos with realistic stats.
 * Mix of languages, sizes, and activity levels.
 * 4-5 are marked as "hot" with trending metrics.
 */
export const DEMO_STARRED_REPOS: Repository[] = [
  // === HOT/TRENDING REPOS (4-5) ===
  {
    id: 10270250,
    name: 'react',
    full_name: 'facebook/react',
    owner: { login: 'facebook', avatar_url: 'https://avatars.githubusercontent.com/u/69631?v=4' },
    description: 'The library for web and native user interfaces.',
    html_url: 'https://github.com/facebook/react',
    stargazers_count: 232000,
    forks_count: 47400,
    watchers_count: 6700,
    open_issues_count: 950,
    language: 'JavaScript',
    license: { key: 'mit', name: 'MIT License', url: 'https://api.github.com/licenses/mit' },
    topics: ['declarative', 'frontend', 'javascript', 'library', 'react', 'ui'],
    updated_at: recentDate(0),
    pushed_at: recentDate(0),
    created_at: '2013-05-24T16:15:54Z',
    starred_at: starredDate(0),
    is_starred: true,
    metrics: {
      is_trending: true,
      stars_growth_rate: 0.018,
      stars_gained: 4200,
      releases_count: 18,
      last_release_date: recentDate(3),
    },
  },
  {
    id: 54346799,
    name: 'supabase',
    full_name: 'supabase/supabase',
    owner: {
      login: 'supabase',
      avatar_url: 'https://avatars.githubusercontent.com/u/54469796?v=4',
    },
    description:
      'The open source Firebase alternative. Supabase gives you a dedicated Postgres database to build your web, mobile, and AI applications.',
    html_url: 'https://github.com/supabase/supabase',
    stargazers_count: 76000,
    forks_count: 7400,
    watchers_count: 520,
    open_issues_count: 420,
    language: 'TypeScript',
    license: {
      key: 'apache-2.0',
      name: 'Apache License 2.0',
      url: 'https://api.github.com/licenses/apache-2.0',
    },
    topics: ['database', 'firebase-alternative', 'postgres', 'realtime', 'supabase'],
    updated_at: recentDate(0),
    pushed_at: recentDate(0),
    created_at: '2020-01-08T17:05:12Z',
    starred_at: starredDate(1),
    is_starred: true,
    metrics: {
      is_trending: true,
      stars_growth_rate: 0.028,
      stars_gained: 2100,
      releases_count: 15,
      last_release_date: recentDate(2),
    },
  },
  {
    id: 120044619,
    name: 'whisper',
    full_name: 'openai/whisper',
    owner: { login: 'openai', avatar_url: 'https://avatars.githubusercontent.com/u/14957082?v=4' },
    description: 'Robust Speech Recognition via Large-Scale Weak Supervision',
    html_url: 'https://github.com/openai/whisper',
    stargazers_count: 74000,
    forks_count: 8800,
    watchers_count: 580,
    open_issues_count: 180,
    language: 'Python',
    license: { key: 'mit', name: 'MIT License', url: 'https://api.github.com/licenses/mit' },
    topics: ['ai', 'machine-learning', 'pytorch', 'speech-recognition', 'transformer'],
    updated_at: recentDate(1),
    pushed_at: recentDate(5),
    created_at: '2022-09-16T21:04:31Z',
    starred_at: starredDate(2),
    is_starred: true,
    metrics: {
      is_trending: true,
      stars_growth_rate: 0.032,
      stars_gained: 2400,
      releases_count: 8,
      last_release_date: recentDate(14),
    },
  },
  {
    id: 36502473,
    name: 'vite',
    full_name: 'vitejs/vite',
    owner: { login: 'vitejs', avatar_url: 'https://avatars.githubusercontent.com/u/65625612?v=4' },
    description: "Next generation frontend tooling. It's fast!",
    html_url: 'https://github.com/vitejs/vite',
    stargazers_count: 71000,
    forks_count: 6400,
    watchers_count: 480,
    open_issues_count: 520,
    language: 'TypeScript',
    license: { key: 'mit', name: 'MIT License', url: 'https://api.github.com/licenses/mit' },
    topics: ['build-tool', 'dev-server', 'esm', 'frontend', 'hmr', 'vite'],
    updated_at: recentDate(0),
    pushed_at: recentDate(0),
    created_at: '2020-04-21T08:45:01Z',
    starred_at: starredDate(3),
    is_starred: true,
    metrics: {
      is_trending: true,
      stars_growth_rate: 0.022,
      stars_gained: 1560,
      releases_count: 22,
      last_release_date: recentDate(1),
    },
  },
  {
    id: 552661142,
    name: 'ollama',
    full_name: 'ollama/ollama',
    owner: { login: 'ollama', avatar_url: 'https://avatars.githubusercontent.com/u/151674099?v=4' },
    description:
      'Get up and running with Llama 3.3, DeepSeek-R1, Phi-4, Gemma 2, and other large language models.',
    html_url: 'https://github.com/ollama/ollama',
    stargazers_count: 115000,
    forks_count: 9200,
    watchers_count: 680,
    open_issues_count: 1200,
    language: 'Go',
    license: { key: 'mit', name: 'MIT License', url: 'https://api.github.com/licenses/mit' },
    topics: ['ai', 'go', 'llama', 'llm', 'local-llm', 'machine-learning'],
    updated_at: recentDate(0),
    pushed_at: recentDate(0),
    created_at: '2023-06-26T17:45:12Z',
    starred_at: starredDate(4),
    is_starred: true,
    metrics: {
      is_trending: true,
      stars_growth_rate: 0.045,
      stars_gained: 5200,
      releases_count: 35,
      last_release_date: recentDate(1),
    },
  },

  // === STABLE POPULAR REPOS ===
  {
    id: 41881900,
    name: 'vscode',
    full_name: 'microsoft/vscode',
    owner: {
      login: 'microsoft',
      avatar_url: 'https://avatars.githubusercontent.com/u/6154722?v=4',
    },
    description: 'Visual Studio Code',
    html_url: 'https://github.com/microsoft/vscode',
    stargazers_count: 167000,
    forks_count: 30000,
    watchers_count: 3300,
    open_issues_count: 8500,
    language: 'TypeScript',
    license: { key: 'mit', name: 'MIT License', url: 'https://api.github.com/licenses/mit' },
    topics: ['editor', 'electron', 'typescript', 'visual-studio-code'],
    updated_at: recentDate(0),
    pushed_at: recentDate(0),
    created_at: '2015-09-03T20:23:38Z',
    starred_at: starredDate(5),
    is_starred: true,
  },
  {
    id: 20929025,
    name: 'TypeScript',
    full_name: 'microsoft/TypeScript',
    owner: {
      login: 'microsoft',
      avatar_url: 'https://avatars.githubusercontent.com/u/6154722?v=4',
    },
    description: 'TypeScript is a superset of JavaScript that compiles to clean JavaScript output.',
    html_url: 'https://github.com/microsoft/TypeScript',
    stargazers_count: 102000,
    forks_count: 12500,
    watchers_count: 2100,
    open_issues_count: 5800,
    language: 'TypeScript',
    license: {
      key: 'apache-2.0',
      name: 'Apache License 2.0',
      url: 'https://api.github.com/licenses/apache-2.0',
    },
    topics: ['javascript', 'language', 'typechecker', 'typescript'],
    updated_at: recentDate(0),
    pushed_at: recentDate(0),
    created_at: '2014-06-17T15:28:39Z',
    starred_at: starredDate(6),
    is_starred: true,
  },
  {
    id: 70107786,
    name: 'next.js',
    full_name: 'vercel/next.js',
    owner: { login: 'vercel', avatar_url: 'https://avatars.githubusercontent.com/u/14985020?v=4' },
    description: 'The React Framework',
    html_url: 'https://github.com/vercel/next.js',
    stargazers_count: 128000,
    forks_count: 27500,
    watchers_count: 1500,
    open_issues_count: 3200,
    language: 'JavaScript',
    license: { key: 'mit', name: 'MIT License', url: 'https://api.github.com/licenses/mit' },
    topics: [
      'blog',
      'compiler',
      'components',
      'hybrid',
      'nextjs',
      'node',
      'react',
      'server-rendering',
      'ssg',
      'static',
      'universal',
      'vercel',
    ],
    updated_at: recentDate(0),
    pushed_at: recentDate(0),
    created_at: '2016-10-05T23:32:51Z',
    starred_at: starredDate(7),
    is_starred: true,
  },
  {
    id: 67274736,
    name: 'tailwindcss',
    full_name: 'tailwindlabs/tailwindcss',
    owner: {
      login: 'tailwindlabs',
      avatar_url: 'https://avatars.githubusercontent.com/u/67109815?v=4',
    },
    description: 'A utility-first CSS framework for rapid UI development.',
    html_url: 'https://github.com/tailwindlabs/tailwindcss',
    stargazers_count: 85000,
    forks_count: 4300,
    watchers_count: 820,
    open_issues_count: 85,
    language: 'TypeScript',
    license: { key: 'mit', name: 'MIT License', url: 'https://api.github.com/licenses/mit' },
    topics: ['css', 'css-framework', 'postcss', 'tailwindcss'],
    updated_at: recentDate(0),
    pushed_at: recentDate(1),
    created_at: '2016-08-15T15:09:46Z',
    starred_at: starredDate(8),
    is_starred: true,
  },
  {
    id: 36040894,
    name: 'query',
    full_name: 'TanStack/query',
    owner: {
      login: 'TanStack',
      avatar_url: 'https://avatars.githubusercontent.com/u/72518640?v=4',
    },
    description:
      'Powerful asynchronous state management, server-state utilities and data fetching for the web.',
    html_url: 'https://github.com/TanStack/query',
    stargazers_count: 43000,
    forks_count: 3000,
    watchers_count: 280,
    open_issues_count: 95,
    language: 'TypeScript',
    license: { key: 'mit', name: 'MIT License', url: 'https://api.github.com/licenses/mit' },
    topics: [
      'async',
      'cache',
      'graphql',
      'hooks',
      'query',
      'react',
      'react-query',
      'rest',
      'stale-while-revalidate',
      'typescript',
    ],
    updated_at: recentDate(0),
    pushed_at: recentDate(1),
    created_at: '2019-02-08T21:37:04Z',
    starred_at: starredDate(9),
    is_starred: true,
  },
  {
    id: 75104123,
    name: 'deno',
    full_name: 'denoland/deno',
    owner: {
      login: 'denoland',
      avatar_url: 'https://avatars.githubusercontent.com/u/42048915?v=4',
    },
    description: 'A modern runtime for JavaScript and TypeScript.',
    html_url: 'https://github.com/denoland/deno',
    stargazers_count: 98000,
    forks_count: 5400,
    watchers_count: 1400,
    open_issues_count: 1900,
    language: 'Rust',
    license: { key: 'mit', name: 'MIT License', url: 'https://api.github.com/licenses/mit' },
    topics: ['deno', 'javascript', 'rust', 'typescript', 'v8'],
    updated_at: recentDate(0),
    pushed_at: recentDate(0),
    created_at: '2018-05-14T09:00:22Z',
    starred_at: starredDate(10),
    is_starred: true,
  },
  {
    id: 74293321,
    name: 'svelte',
    full_name: 'sveltejs/svelte',
    owner: {
      login: 'sveltejs',
      avatar_url: 'https://avatars.githubusercontent.com/u/23617963?v=4',
    },
    description: 'web development for the rest of us',
    html_url: 'https://github.com/sveltejs/svelte',
    stargazers_count: 81000,
    forks_count: 4300,
    watchers_count: 850,
    open_issues_count: 950,
    language: 'JavaScript',
    license: { key: 'mit', name: 'MIT License', url: 'https://api.github.com/licenses/mit' },
    topics: ['compiler', 'javascript', 'svelte', 'ui'],
    updated_at: recentDate(0),
    pushed_at: recentDate(0),
    created_at: '2016-11-20T18:13:05Z',
    starred_at: starredDate(11),
    is_starred: true,
  },
  {
    id: 83222441,
    name: 'remix',
    full_name: 'remix-run/remix',
    owner: {
      login: 'remix-run',
      avatar_url: 'https://avatars.githubusercontent.com/u/64235328?v=4',
    },
    description:
      'Build Better Websites. Create modern, resilient user experiences with web fundamentals.',
    html_url: 'https://github.com/remix-run/remix',
    stargazers_count: 30500,
    forks_count: 2600,
    watchers_count: 230,
    open_issues_count: 180,
    language: 'TypeScript',
    license: { key: 'mit', name: 'MIT License', url: 'https://api.github.com/licenses/mit' },
    topics: ['framework', 'nested-routes', 'react', 'remix', 'remix-run', 'ssr', 'web'],
    updated_at: recentDate(0),
    pushed_at: recentDate(1),
    created_at: '2020-10-26T20:55:36Z',
    starred_at: starredDate(12),
    is_starred: true,
  },
  {
    id: 83827139,
    name: 'zustand',
    full_name: 'pmndrs/zustand',
    owner: { login: 'pmndrs', avatar_url: 'https://avatars.githubusercontent.com/u/45790596?v=4' },
    description: 'Bear necessities for state management in React',
    html_url: 'https://github.com/pmndrs/zustand',
    stargazers_count: 49000,
    forks_count: 1500,
    watchers_count: 210,
    open_issues_count: 12,
    language: 'TypeScript',
    license: { key: 'mit', name: 'MIT License', url: 'https://api.github.com/licenses/mit' },
    topics: ['flux', 'hooks', 'react', 'state', 'store', 'zustand'],
    updated_at: recentDate(1),
    pushed_at: recentDate(3),
    created_at: '2019-04-09T07:40:13Z',
    starred_at: starredDate(13),
    is_starred: true,
  },
  {
    id: 205941985,
    name: 'zod',
    full_name: 'colinhacks/zod',
    owner: {
      login: 'colinhacks',
      avatar_url: 'https://avatars.githubusercontent.com/u/3084745?v=4',
    },
    description: 'TypeScript-first schema validation with static type inference',
    html_url: 'https://github.com/colinhacks/zod',
    stargazers_count: 35000,
    forks_count: 1200,
    watchers_count: 140,
    open_issues_count: 580,
    language: 'TypeScript',
    license: { key: 'mit', name: 'MIT License', url: 'https://api.github.com/licenses/mit' },
    topics: ['schema', 'typescript', 'validation', 'zod'],
    updated_at: recentDate(0),
    pushed_at: recentDate(2),
    created_at: '2020-03-07T02:14:55Z',
    starred_at: starredDate(14),
    is_starred: true,
  },
  {
    id: 576201,
    name: 'django',
    full_name: 'django/django',
    owner: { login: 'django', avatar_url: 'https://avatars.githubusercontent.com/u/27804?v=4' },
    description: 'The Web framework for perfectionists with deadlines.',
    html_url: 'https://github.com/django/django',
    stargazers_count: 82000,
    forks_count: 32000,
    watchers_count: 2400,
    open_issues_count: 250,
    language: 'Python',
    license: {
      key: 'bsd-3-clause',
      name: 'BSD 3-Clause "New" or "Revised" License',
      url: 'https://api.github.com/licenses/bsd-3-clause',
    },
    topics: ['apps', 'django', 'framework', 'models', 'orm', 'python', 'templates', 'views', 'web'],
    updated_at: recentDate(0),
    pushed_at: recentDate(0),
    created_at: '2012-04-28T02:47:18Z',
    starred_at: starredDate(15),
    is_starred: true,
  },
  {
    id: 596892,
    name: 'flask',
    full_name: 'pallets/flask',
    owner: { login: 'pallets', avatar_url: 'https://avatars.githubusercontent.com/u/16748505?v=4' },
    description: 'The Python micro framework for building web applications.',
    html_url: 'https://github.com/pallets/flask',
    stargazers_count: 69000,
    forks_count: 16200,
    watchers_count: 2100,
    open_issues_count: 8,
    language: 'Python',
    license: {
      key: 'bsd-3-clause',
      name: 'BSD 3-Clause "New" or "Revised" License',
      url: 'https://api.github.com/licenses/bsd-3-clause',
    },
    topics: ['flask', 'jinja', 'pallets', 'python', 'web-framework', 'werkzeug', 'wsgi'],
    updated_at: recentDate(1),
    pushed_at: recentDate(5),
    created_at: '2010-04-06T11:11:59Z',
    starred_at: starredDate(16),
    is_starred: true,
  },
  {
    id: 236892675,
    name: 'fastapi',
    full_name: 'fastapi/fastapi',
    owner: {
      login: 'fastapi',
      avatar_url: 'https://avatars.githubusercontent.com/u/156354296?v=4',
    },
    description:
      'FastAPI framework, high performance, easy to learn, fast to code, ready for production',
    html_url: 'https://github.com/fastapi/fastapi',
    stargazers_count: 80000,
    forks_count: 6800,
    watchers_count: 600,
    open_issues_count: 520,
    language: 'Python',
    license: { key: 'mit', name: 'MIT License', url: 'https://api.github.com/licenses/mit' },
    topics: [
      'api',
      'async',
      'asyncio',
      'fastapi',
      'framework',
      'json',
      'openapi',
      'pydantic',
      'python',
      'rest',
      'starlette',
      'swagger',
      'uvicorn',
      'web',
    ],
    updated_at: recentDate(0),
    pushed_at: recentDate(1),
    created_at: '2018-12-08T14:02:29Z',
    starred_at: starredDate(17),
    is_starred: true,
  },
  {
    id: 1181927,
    name: 'requests',
    full_name: 'psf/requests',
    owner: { login: 'psf', avatar_url: 'https://avatars.githubusercontent.com/u/50630501?v=4' },
    description: 'A simple, yet elegant, HTTP library.',
    html_url: 'https://github.com/psf/requests',
    stargazers_count: 52500,
    forks_count: 9300,
    watchers_count: 1300,
    open_issues_count: 320,
    language: 'Python',
    license: {
      key: 'apache-2.0',
      name: 'Apache License 2.0',
      url: 'https://api.github.com/licenses/apache-2.0',
    },
    topics: [
      'client',
      'cookies',
      'forhumans',
      'http',
      'humans',
      'python',
      'python-requests',
      'requests',
    ],
    updated_at: recentDate(2),
    pushed_at: recentDate(7),
    created_at: '2011-02-13T18:38:17Z',
    starred_at: starredDate(18),
    is_starred: true,
  },
  {
    id: 458058,
    name: 'rust',
    full_name: 'rust-lang/rust',
    owner: {
      login: 'rust-lang',
      avatar_url: 'https://avatars.githubusercontent.com/u/5430905?v=4',
    },
    description: 'Empowering everyone to build reliable and efficient software.',
    html_url: 'https://github.com/rust-lang/rust',
    stargazers_count: 100000,
    forks_count: 13000,
    watchers_count: 1500,
    open_issues_count: 10500,
    language: 'Rust',
    license: { key: 'other', name: 'Other', url: null },
    topics: ['compiler', 'language', 'rust'],
    updated_at: recentDate(0),
    pushed_at: recentDate(0),
    created_at: '2010-06-16T20:39:03Z',
    starred_at: starredDate(19),
    is_starred: true,
  },
  {
    id: 19816070,
    name: 'ripgrep',
    full_name: 'BurntSushi/ripgrep',
    owner: {
      login: 'BurntSushi',
      avatar_url: 'https://avatars.githubusercontent.com/u/456674?v=4',
    },
    description:
      'ripgrep recursively searches directories for a regex pattern while respecting your gitignore',
    html_url: 'https://github.com/BurntSushi/ripgrep',
    stargazers_count: 50000,
    forks_count: 2100,
    watchers_count: 420,
    open_issues_count: 120,
    language: 'Rust',
    license: {
      key: 'unlicense',
      name: 'The Unlicense',
      url: 'https://api.github.com/licenses/unlicense',
    },
    topics: ['cli', 'grep', 'regex', 'ripgrep', 'rust', 'search', 'tool'],
    updated_at: recentDate(1),
    pushed_at: recentDate(14),
    created_at: '2016-03-11T05:36:49Z',
    starred_at: starredDate(20),
    is_starred: true,
  },
  {
    id: 215574951,
    name: 'tauri',
    full_name: 'tauri-apps/tauri',
    owner: {
      login: 'tauri-apps',
      avatar_url: 'https://avatars.githubusercontent.com/u/54536011?v=4',
    },
    description:
      'Build smaller, faster, and more secure desktop and mobile applications with a web frontend.',
    html_url: 'https://github.com/tauri-apps/tauri',
    stargazers_count: 88000,
    forks_count: 2700,
    watchers_count: 520,
    open_issues_count: 950,
    language: 'Rust',
    license: {
      key: 'apache-2.0',
      name: 'Apache License 2.0',
      url: 'https://api.github.com/licenses/apache-2.0',
    },
    topics: ['desktop-app', 'electron-alternative', 'mobile', 'rust', 'tauri', 'webview'],
    updated_at: recentDate(0),
    pushed_at: recentDate(0),
    created_at: '2019-10-17T22:47:21Z',
    starred_at: starredDate(21),
    is_starred: true,
  },
  {
    id: 23096959,
    name: 'golang',
    full_name: 'golang/go',
    owner: { login: 'golang', avatar_url: 'https://avatars.githubusercontent.com/u/4314092?v=4' },
    description: 'The Go programming language',
    html_url: 'https://github.com/golang/go',
    stargazers_count: 125000,
    forks_count: 17800,
    watchers_count: 3500,
    open_issues_count: 9200,
    language: 'Go',
    license: {
      key: 'bsd-3-clause',
      name: 'BSD 3-Clause "New" or "Revised" License',
      url: 'https://api.github.com/licenses/bsd-3-clause',
    },
    topics: ['go', 'golang', 'language', 'programming-language'],
    updated_at: recentDate(0),
    pushed_at: recentDate(0),
    created_at: '2014-08-19T04:33:40Z',
    starred_at: starredDate(22),
    is_starred: true,
  },
  {
    id: 377694603,
    name: 'transformers',
    full_name: 'huggingface/transformers',
    owner: {
      login: 'huggingface',
      avatar_url: 'https://avatars.githubusercontent.com/u/25720743?v=4',
    },
    description:
      'Transformers: State-of-the-art Machine Learning for Pytorch, TensorFlow, and JAX.',
    html_url: 'https://github.com/huggingface/transformers',
    stargazers_count: 138000,
    forks_count: 27500,
    watchers_count: 1200,
    open_issues_count: 1400,
    language: 'Python',
    license: {
      key: 'apache-2.0',
      name: 'Apache License 2.0',
      url: 'https://api.github.com/licenses/apache-2.0',
    },
    topics: [
      'bert',
      'deep-learning',
      'flax',
      'gpt',
      'jax',
      'language-model',
      'llm',
      'machine-learning',
      'nlp',
      'pytorch',
      'tensorflow',
      'transformer',
    ],
    updated_at: recentDate(0),
    pushed_at: recentDate(0),
    created_at: '2018-10-29T13:56:00Z',
    starred_at: starredDate(23),
    is_starred: true,
  },
  {
    id: 548162057,
    name: 'langchain',
    full_name: 'langchain-ai/langchain',
    owner: {
      login: 'langchain-ai',
      avatar_url: 'https://avatars.githubusercontent.com/u/126733545?v=4',
    },
    description: 'Build context-aware reasoning applications',
    html_url: 'https://github.com/langchain-ai/langchain',
    stargazers_count: 98000,
    forks_count: 15800,
    watchers_count: 750,
    open_issues_count: 980,
    language: 'Python',
    license: { key: 'mit', name: 'MIT License', url: 'https://api.github.com/licenses/mit' },
    topics: ['agents', 'ai', 'composability', 'gpt', 'langchain', 'llm', 'openai', 'python', 'rag'],
    updated_at: recentDate(0),
    pushed_at: recentDate(0),
    created_at: '2022-10-17T02:58:36Z',
    starred_at: starredDate(24),
    is_starred: true,
  },
  {
    id: 28457823,
    name: 'freeCodeCamp',
    full_name: 'freeCodeCamp/freeCodeCamp',
    owner: {
      login: 'freeCodeCamp',
      avatar_url: 'https://avatars.githubusercontent.com/u/9892522?v=4',
    },
    description: "freeCodeCamp.org's open-source codebase and curriculum. Learn to code for free.",
    html_url: 'https://github.com/freeCodeCamp/freeCodeCamp',
    stargazers_count: 410000,
    forks_count: 38500,
    watchers_count: 8500,
    open_issues_count: 320,
    language: 'TypeScript',
    license: {
      key: 'bsd-3-clause',
      name: 'BSD 3-Clause "New" or "Revised" License',
      url: 'https://api.github.com/licenses/bsd-3-clause',
    },
    topics: [
      'careers',
      'certification',
      'community',
      'curriculum',
      'education',
      'freecodecamp',
      'javascript',
      'learn-to-code',
      'math',
      'nonprofits',
      'programming',
      'teachers',
    ],
    updated_at: recentDate(0),
    pushed_at: recentDate(0),
    created_at: '2014-12-24T17:49:19Z',
    starred_at: starredDate(25),
    is_starred: true,
  },
  {
    id: 63537249,
    name: 'javascript-algorithms',
    full_name: 'trekhleb/javascript-algorithms',
    owner: { login: 'trekhleb', avatar_url: 'https://avatars.githubusercontent.com/u/3000285?v=4' },
    description:
      'Algorithms and data structures implemented in JavaScript with explanations and links to further readings',
    html_url: 'https://github.com/trekhleb/javascript-algorithms',
    stargazers_count: 190000,
    forks_count: 31000,
    watchers_count: 3500,
    open_issues_count: 250,
    language: 'JavaScript',
    license: { key: 'mit', name: 'MIT License', url: 'https://api.github.com/licenses/mit' },
    topics: [
      'algorithm',
      'algorithms',
      'computer-science',
      'data-structures',
      'interview',
      'interview-preparation',
      'javascript',
      'javascript-algorithms',
    ],
    updated_at: recentDate(2),
    pushed_at: recentDate(10),
    created_at: '2018-03-24T07:47:05Z',
    starred_at: starredDate(26),
    is_starred: true,
  },
  {
    id: 29028775,
    name: 'react-router',
    full_name: 'remix-run/react-router',
    owner: {
      login: 'remix-run',
      avatar_url: 'https://avatars.githubusercontent.com/u/64235328?v=4',
    },
    description: 'Declarative routing for React',
    html_url: 'https://github.com/remix-run/react-router',
    stargazers_count: 53500,
    forks_count: 10400,
    watchers_count: 890,
    open_issues_count: 180,
    language: 'TypeScript',
    license: { key: 'mit', name: 'MIT License', url: 'https://api.github.com/licenses/mit' },
    topics: ['react', 'react-router', 'routing'],
    updated_at: recentDate(0),
    pushed_at: recentDate(1),
    created_at: '2014-05-16T22:22:51Z',
    starred_at: starredDate(27),
    is_starred: true,
  },
  {
    id: 14985020,
    name: 'redux',
    full_name: 'reduxjs/redux',
    owner: { login: 'reduxjs', avatar_url: 'https://avatars.githubusercontent.com/u/13142323?v=4' },
    description: 'A JS library for predictable global state management',
    html_url: 'https://github.com/reduxjs/redux',
    stargazers_count: 60800,
    forks_count: 15400,
    watchers_count: 1300,
    open_issues_count: 45,
    language: 'TypeScript',
    license: { key: 'mit', name: 'MIT License', url: 'https://api.github.com/licenses/mit' },
    topics: ['flux', 'predictable', 'react', 'redux', 'state', 'state-management'],
    updated_at: recentDate(3),
    pushed_at: recentDate(14),
    created_at: '2015-05-29T23:53:15Z',
    starred_at: starredDate(28),
    is_starred: true,
  },
  {
    id: 75396575,
    name: 'react-hook-form',
    full_name: 'react-hook-form/react-hook-form',
    owner: {
      login: 'react-hook-form',
      avatar_url: 'https://avatars.githubusercontent.com/u/53986236?v=4',
    },
    description: 'React Hooks for form state management and validation (Web + React Native)',
    html_url: 'https://github.com/react-hook-form/react-hook-form',
    stargazers_count: 42500,
    forks_count: 2100,
    watchers_count: 210,
    open_issues_count: 45,
    language: 'TypeScript',
    license: { key: 'mit', name: 'MIT License', url: 'https://api.github.com/licenses/mit' },
    topics: [
      'dx',
      'form',
      'form-validation',
      'forms',
      'hooks',
      'performance',
      'react',
      'react-hooks',
      'react-native',
      'reactjs',
      'typescript',
      'ux',
      'validation',
    ],
    updated_at: recentDate(0),
    pushed_at: recentDate(2),
    created_at: '2019-03-13T15:04:34Z',
    starred_at: starredDate(29),
    is_starred: true,
  },
  {
    id: 237159,
    name: 'prettier',
    full_name: 'prettier/prettier',
    owner: {
      login: 'prettier',
      avatar_url: 'https://avatars.githubusercontent.com/u/25822731?v=4',
    },
    description: 'Prettier is an opinionated code formatter.',
    html_url: 'https://github.com/prettier/prettier',
    stargazers_count: 50000,
    forks_count: 4400,
    watchers_count: 480,
    open_issues_count: 1400,
    language: 'JavaScript',
    license: { key: 'mit', name: 'MIT License', url: 'https://api.github.com/licenses/mit' },
    topics: [
      'angular',
      'ast',
      'css',
      'formatter',
      'graphql',
      'html',
      'javascript',
      'json',
      'jsx',
      'less',
      'markdown',
      'prettier',
      'printer',
      'scss',
      'typescript',
      'vue',
      'yaml',
    ],
    updated_at: recentDate(0),
    pushed_at: recentDate(1),
    created_at: '2016-01-29T00:00:00Z',
    starred_at: starredDate(30),
    is_starred: true,
  },
  {
    id: 11730342,
    name: 'eslint',
    full_name: 'eslint/eslint',
    owner: { login: 'eslint', avatar_url: 'https://avatars.githubusercontent.com/u/6019716?v=4' },
    description: 'Find and fix problems in your JavaScript code.',
    html_url: 'https://github.com/eslint/eslint',
    stargazers_count: 25500,
    forks_count: 4600,
    watchers_count: 330,
    open_issues_count: 120,
    language: 'JavaScript',
    license: { key: 'mit', name: 'MIT License', url: 'https://api.github.com/licenses/mit' },
    topics: ['ecmascript', 'eslint', 'javascript', 'linter', 'nodejs', 'static-analysis'],
    updated_at: recentDate(0),
    pushed_at: recentDate(0),
    created_at: '2013-07-25T03:44:24Z',
    starred_at: starredDate(31),
    is_starred: true,
  },
  {
    id: 51148780,
    name: 'playwright',
    full_name: 'microsoft/playwright',
    owner: {
      login: 'microsoft',
      avatar_url: 'https://avatars.githubusercontent.com/u/6154722?v=4',
    },
    description: 'Playwright is a framework for Web Testing and Automation.',
    html_url: 'https://github.com/microsoft/playwright',
    stargazers_count: 69000,
    forks_count: 3800,
    watchers_count: 420,
    open_issues_count: 750,
    language: 'TypeScript',
    license: {
      key: 'apache-2.0',
      name: 'Apache License 2.0',
      url: 'https://api.github.com/licenses/apache-2.0',
    },
    topics: [
      'automation',
      'chromium',
      'e2e-testing',
      'end-to-end-testing',
      'firefox',
      'playwright',
      'testing',
      'webkit',
    ],
    updated_at: recentDate(0),
    pushed_at: recentDate(0),
    created_at: '2020-01-22T16:00:00Z',
    starred_at: starredDate(32),
    is_starred: true,
  },
  {
    id: 157846876,
    name: 'vitest',
    full_name: 'vitest-dev/vitest',
    owner: {
      login: 'vitest-dev',
      avatar_url: 'https://avatars.githubusercontent.com/u/95747107?v=4',
    },
    description: 'Next generation testing framework powered by Vite.',
    html_url: 'https://github.com/vitest-dev/vitest',
    stargazers_count: 14000,
    forks_count: 1300,
    watchers_count: 65,
    open_issues_count: 380,
    language: 'TypeScript',
    license: { key: 'mit', name: 'MIT License', url: 'https://api.github.com/licenses/mit' },
    topics: ['coverage', 'jest', 'snapshot', 'test', 'testing', 'typescript', 'vite', 'vitest'],
    updated_at: recentDate(0),
    pushed_at: recentDate(0),
    created_at: '2021-12-03T06:48:38Z',
    starred_at: starredDate(33),
    is_starred: true,
  },
  {
    id: 99766187,
    name: 'headlessui',
    full_name: 'tailwindlabs/headlessui',
    owner: {
      login: 'tailwindlabs',
      avatar_url: 'https://avatars.githubusercontent.com/u/67109815?v=4',
    },
    description:
      'Completely unstyled, fully accessible UI components, designed to integrate beautifully with Tailwind CSS.',
    html_url: 'https://github.com/tailwindlabs/headlessui',
    stargazers_count: 26500,
    forks_count: 1100,
    watchers_count: 150,
    open_issues_count: 35,
    language: 'TypeScript',
    license: { key: 'mit', name: 'MIT License', url: 'https://api.github.com/licenses/mit' },
    topics: ['accessibility', 'headless', 'react', 'tailwindcss', 'ui-components', 'vue'],
    updated_at: recentDate(1),
    pushed_at: recentDate(3),
    created_at: '2020-08-12T03:59:13Z',
    starred_at: starredDate(34),
    is_starred: true,
  },
  {
    id: 143244109,
    name: 'trpc',
    full_name: 'trpc/trpc',
    owner: { login: 'trpc', avatar_url: 'https://avatars.githubusercontent.com/u/78011399?v=4' },
    description: 'Move Fast and Break Nothing. End-to-end typesafe APIs made easy.',
    html_url: 'https://github.com/trpc/trpc',
    stargazers_count: 35500,
    forks_count: 1300,
    watchers_count: 140,
    open_issues_count: 130,
    language: 'TypeScript',
    license: { key: 'mit', name: 'MIT License', url: 'https://api.github.com/licenses/mit' },
    topics: ['api', 'nextjs', 'react', 'rpc', 'trpc', 'typescript'],
    updated_at: recentDate(0),
    pushed_at: recentDate(1),
    created_at: '2020-07-18T03:11:02Z',
    starred_at: starredDate(35),
    is_starred: true,
  },
  {
    id: 156018,
    name: 'lodash',
    full_name: 'lodash/lodash',
    owner: { login: 'lodash', avatar_url: 'https://avatars.githubusercontent.com/u/2565403?v=4' },
    description:
      'A modern JavaScript utility library delivering modularity, performance, & extras.',
    html_url: 'https://github.com/lodash/lodash',
    stargazers_count: 60000,
    forks_count: 7100,
    watchers_count: 900,
    open_issues_count: 450,
    language: 'JavaScript',
    license: { key: 'mit', name: 'MIT License', url: 'https://api.github.com/licenses/mit' },
    topics: ['javascript', 'lodash', 'modules', 'utilities'],
    updated_at: recentDate(5),
    pushed_at: recentDate(30),
    created_at: '2012-04-07T04:01:32Z',
    starred_at: starredDate(36),
    is_starred: true,
  },
  {
    id: 83874295,
    name: 'axios',
    full_name: 'axios/axios',
    owner: { login: 'axios', avatar_url: 'https://avatars.githubusercontent.com/u/32372333?v=4' },
    description: 'Promise based HTTP client for the browser and node.js',
    html_url: 'https://github.com/axios/axios',
    stargazers_count: 106000,
    forks_count: 11000,
    watchers_count: 1100,
    open_issues_count: 680,
    language: 'JavaScript',
    license: { key: 'mit', name: 'MIT License', url: 'https://api.github.com/licenses/mit' },
    topics: ['http', 'http-client', 'javascript', 'nodejs', 'promise', 'xhr'],
    updated_at: recentDate(1),
    pushed_at: recentDate(3),
    created_at: '2014-08-18T22:30:27Z',
    starred_at: starredDate(37),
    is_starred: true,
  },
  {
    id: 8514,
    name: 'rails',
    full_name: 'rails/rails',
    owner: { login: 'rails', avatar_url: 'https://avatars.githubusercontent.com/u/4223?v=4' },
    description: 'Ruby on Rails',
    html_url: 'https://github.com/rails/rails',
    stargazers_count: 56500,
    forks_count: 21700,
    watchers_count: 2400,
    open_issues_count: 720,
    language: 'Ruby',
    license: { key: 'mit', name: 'MIT License', url: 'https://api.github.com/licenses/mit' },
    topics: ['activejob', 'activerecord', 'framework', 'html', 'mvc', 'rails', 'ruby'],
    updated_at: recentDate(0),
    pushed_at: recentDate(0),
    created_at: '2008-04-11T02:19:47Z',
    starred_at: starredDate(38),
    is_starred: true,
  },
  {
    id: 460078,
    name: 'rustlings',
    full_name: 'rust-lang/rustlings',
    owner: {
      login: 'rust-lang',
      avatar_url: 'https://avatars.githubusercontent.com/u/5430905?v=4',
    },
    description: 'Small exercises to get you used to reading and writing Rust code!',
    html_url: 'https://github.com/rust-lang/rustlings',
    stargazers_count: 55000,
    forks_count: 10500,
    watchers_count: 380,
    open_issues_count: 45,
    language: 'Rust',
    license: { key: 'mit', name: 'MIT License', url: 'https://api.github.com/licenses/mit' },
    topics: ['beginner-friendly', 'education', 'exercises', 'rust', 'rustlings'],
    updated_at: recentDate(1),
    pushed_at: recentDate(5),
    created_at: '2018-01-23T09:00:00Z',
    starred_at: starredDate(39),
    is_starred: true,
  },
  {
    id: 111583593,
    name: 'storybook',
    full_name: 'storybookjs/storybook',
    owner: {
      login: 'storybookjs',
      avatar_url: 'https://avatars.githubusercontent.com/u/22632046?v=4',
    },
    description:
      'Storybook is the industry standard workshop for building, documenting, and testing UI components in isolation',
    html_url: 'https://github.com/storybookjs/storybook',
    stargazers_count: 85500,
    forks_count: 9400,
    watchers_count: 680,
    open_issues_count: 1900,
    language: 'TypeScript',
    license: { key: 'mit', name: 'MIT License', url: 'https://api.github.com/licenses/mit' },
    topics: [
      'angular',
      'components',
      'design-systems',
      'documentation',
      'frontend',
      'react',
      'storybook',
      'svelte',
      'testing',
      'ui',
      'vue',
    ],
    updated_at: recentDate(0),
    pushed_at: recentDate(0),
    created_at: '2016-04-06T04:08:24Z',
    starred_at: starredDate(40),
    is_starred: true,
  },
  {
    id: 34526884,
    name: 'excalidraw',
    full_name: 'excalidraw/excalidraw',
    owner: {
      login: 'excalidraw',
      avatar_url: 'https://avatars.githubusercontent.com/u/59452120?v=4',
    },
    description: 'Virtual whiteboard for sketching hand-drawn like diagrams',
    html_url: 'https://github.com/excalidraw/excalidraw',
    stargazers_count: 89000,
    forks_count: 8600,
    watchers_count: 420,
    open_issues_count: 1600,
    language: 'TypeScript',
    license: { key: 'mit', name: 'MIT License', url: 'https://api.github.com/licenses/mit' },
    topics: [
      'canvas',
      'collaboration',
      'diagrams',
      'drawing',
      'excalidraw',
      'hand-drawn',
      'productivity',
      'react',
      'sketch',
      'whiteboard',
    ],
    updated_at: recentDate(0),
    pushed_at: recentDate(0),
    created_at: '2020-01-01T20:14:35Z',
    starred_at: starredDate(41),
    is_starred: true,
  },
  {
    id: 11225014,
    name: 'socket.io',
    full_name: 'socketio/socket.io',
    owner: {
      login: 'socketio',
      avatar_url: 'https://avatars.githubusercontent.com/u/10566080?v=4',
    },
    description: 'Realtime application framework (Node.JS server)',
    html_url: 'https://github.com/socketio/socket.io',
    stargazers_count: 61500,
    forks_count: 10200,
    watchers_count: 1500,
    open_issues_count: 180,
    language: 'TypeScript',
    license: { key: 'mit', name: 'MIT License', url: 'https://api.github.com/licenses/mit' },
    topics: ['javascript', 'nodejs', 'realtime', 'socket', 'websocket'],
    updated_at: recentDate(2),
    pushed_at: recentDate(7),
    created_at: '2010-03-11T18:24:48Z',
    starred_at: starredDate(42),
    is_starred: true,
  },
  {
    id: 137078487,
    name: 'prisma',
    full_name: 'prisma/prisma',
    owner: { login: 'prisma', avatar_url: 'https://avatars.githubusercontent.com/u/17219288?v=4' },
    description:
      'Next-generation ORM for Node.js & TypeScript | PostgreSQL, MySQL, MariaDB, SQL Server, SQLite, MongoDB and CockroachDB',
    html_url: 'https://github.com/prisma/prisma',
    stargazers_count: 40500,
    forks_count: 1600,
    watchers_count: 240,
    open_issues_count: 3200,
    language: 'TypeScript',
    license: {
      key: 'apache-2.0',
      name: 'Apache License 2.0',
      url: 'https://api.github.com/licenses/apache-2.0',
    },
    topics: [
      'database',
      'graphql',
      'mysql',
      'nodejs',
      'orm',
      'postgresql',
      'prisma',
      'sql',
      'typescript',
    ],
    updated_at: recentDate(0),
    pushed_at: recentDate(0),
    created_at: '2018-06-08T08:41:58Z',
    starred_at: starredDate(43),
    is_starred: true,
  },
  {
    id: 10378980,
    name: 'moby',
    full_name: 'moby/moby',
    owner: { login: 'moby', avatar_url: 'https://avatars.githubusercontent.com/u/27530802?v=4' },
    description:
      'The Moby Project - a collaborative project for the container ecosystem to assemble container-based systems',
    html_url: 'https://github.com/moby/moby',
    stargazers_count: 69000,
    forks_count: 18800,
    watchers_count: 3000,
    open_issues_count: 3500,
    language: 'Go',
    license: {
      key: 'apache-2.0',
      name: 'Apache License 2.0',
      url: 'https://api.github.com/licenses/apache-2.0',
    },
    topics: ['containers', 'docker', 'go', 'moby'],
    updated_at: recentDate(0),
    pushed_at: recentDate(0),
    created_at: '2013-01-18T18:10:57Z',
    starred_at: starredDate(44),
    is_starred: true,
  },
];

// === RADARS ===
export const DEMO_RADARS: RadarWithCount[] = [
  {
    id: 'demo-radar-frontend',
    user_id: DEMO_USER.id,
    name: 'Frontend Tools',
    created_at: recentDate(60),
    updated_at: recentDate(2),
    repo_count: 12,
  },
  {
    id: 'demo-radar-learning',
    user_id: DEMO_USER.id,
    name: 'Learning Resources',
    created_at: recentDate(45),
    updated_at: recentDate(5),
    repo_count: 5,
  },
];

// Radar repo associations
export const DEMO_RADAR_REPOS: RadarRepo[] = [
  // Frontend Tools (12 repos)
  {
    id: 'rr-1',
    radar_id: 'demo-radar-frontend',
    github_repo_id: 10270250,
    added_at: recentDate(55),
  }, // react
  {
    id: 'rr-2',
    radar_id: 'demo-radar-frontend',
    github_repo_id: 36502473,
    added_at: recentDate(54),
  }, // vite
  {
    id: 'rr-3',
    radar_id: 'demo-radar-frontend',
    github_repo_id: 67274736,
    added_at: recentDate(53),
  }, // tailwindcss
  {
    id: 'rr-4',
    radar_id: 'demo-radar-frontend',
    github_repo_id: 70107786,
    added_at: recentDate(52),
  }, // next.js
  {
    id: 'rr-5',
    radar_id: 'demo-radar-frontend',
    github_repo_id: 36040894,
    added_at: recentDate(51),
  }, // tanstack query
  {
    id: 'rr-6',
    radar_id: 'demo-radar-frontend',
    github_repo_id: 83827139,
    added_at: recentDate(50),
  }, // zustand
  {
    id: 'rr-7',
    radar_id: 'demo-radar-frontend',
    github_repo_id: 29028775,
    added_at: recentDate(49),
  }, // react-router
  {
    id: 'rr-8',
    radar_id: 'demo-radar-frontend',
    github_repo_id: 75396575,
    added_at: recentDate(48),
  }, // react-hook-form
  {
    id: 'rr-9',
    radar_id: 'demo-radar-frontend',
    github_repo_id: 99766187,
    added_at: recentDate(47),
  }, // headlessui
  {
    id: 'rr-10',
    radar_id: 'demo-radar-frontend',
    github_repo_id: 143244109,
    added_at: recentDate(46),
  }, // trpc
  {
    id: 'rr-11',
    radar_id: 'demo-radar-frontend',
    github_repo_id: 157846876,
    added_at: recentDate(45),
  }, // vitest
  {
    id: 'rr-12',
    radar_id: 'demo-radar-frontend',
    github_repo_id: 111583593,
    added_at: recentDate(44),
  }, // storybook

  // Learning Resources (5 repos)
  {
    id: 'rr-13',
    radar_id: 'demo-radar-learning',
    github_repo_id: 28457823,
    added_at: recentDate(40),
  }, // freeCodeCamp
  {
    id: 'rr-14',
    radar_id: 'demo-radar-learning',
    github_repo_id: 63537249,
    added_at: recentDate(39),
  }, // javascript-algorithms
  {
    id: 'rr-15',
    radar_id: 'demo-radar-learning',
    github_repo_id: 460078,
    added_at: recentDate(38),
  }, // rustlings
  {
    id: 'rr-16',
    radar_id: 'demo-radar-learning',
    github_repo_id: 20929025,
    added_at: recentDate(37),
  }, // typescript
  {
    id: 'rr-17',
    radar_id: 'demo-radar-learning',
    github_repo_id: 458058,
    added_at: recentDate(36),
  }, // rust
];

// === SEARCH RESULTS ===

// Additional repos for search that aren't in starred list
const ADDITIONAL_SEARCH_REPOS: Repository[] = [
  {
    id: 49609581,
    name: 'vue',
    full_name: 'vuejs/core',
    owner: { login: 'vuejs', avatar_url: 'https://avatars.githubusercontent.com/u/6128107?v=4' },
    description: 'The progressive JavaScript framework for building modern web UI',
    html_url: 'https://github.com/vuejs/core',
    stargazers_count: 48000,
    forks_count: 8400,
    watchers_count: 1100,
    open_issues_count: 720,
    language: 'TypeScript',
    license: { key: 'mit', name: 'MIT License', url: 'https://api.github.com/licenses/mit' },
    topics: ['framework', 'frontend', 'javascript', 'vue'],
    updated_at: recentDate(0),
    pushed_at: recentDate(0),
    created_at: '2018-09-25T00:00:00Z',
    is_starred: false,
  },
  {
    id: 24195339,
    name: 'angular',
    full_name: 'angular/angular',
    owner: { login: 'angular', avatar_url: 'https://avatars.githubusercontent.com/u/139426?v=4' },
    description: "The modern web developer's platform",
    html_url: 'https://github.com/angular/angular',
    stargazers_count: 96500,
    forks_count: 25600,
    watchers_count: 3100,
    open_issues_count: 1700,
    language: 'TypeScript',
    license: { key: 'mit', name: 'MIT License', url: 'https://api.github.com/licenses/mit' },
    topics: ['angular', 'framework', 'javascript', 'typescript', 'web'],
    updated_at: recentDate(0),
    pushed_at: recentDate(0),
    created_at: '2014-09-18T16:12:01Z',
    is_starred: false,
  },
  {
    id: 143451541,
    name: 'pytorch',
    full_name: 'pytorch/pytorch',
    owner: { login: 'pytorch', avatar_url: 'https://avatars.githubusercontent.com/u/21003710?v=4' },
    description: 'Tensors and Dynamic neural networks in Python with strong GPU acceleration',
    html_url: 'https://github.com/pytorch/pytorch',
    stargazers_count: 86000,
    forks_count: 23200,
    watchers_count: 1600,
    open_issues_count: 15500,
    language: 'Python',
    license: { key: 'other', name: 'Other', url: null },
    topics: [
      'autograd',
      'deep-learning',
      'gpu',
      'machine-learning',
      'neural-network',
      'numpy',
      'python',
      'pytorch',
      'tensor',
    ],
    updated_at: recentDate(0),
    pushed_at: recentDate(0),
    created_at: '2016-08-13T05:26:41Z',
    is_starred: false,
  },
  {
    id: 45717250,
    name: 'tensorflow',
    full_name: 'tensorflow/tensorflow',
    owner: {
      login: 'tensorflow',
      avatar_url: 'https://avatars.githubusercontent.com/u/15658638?v=4',
    },
    description: 'An Open Source Machine Learning Framework for Everyone',
    html_url: 'https://github.com/tensorflow/tensorflow',
    stargazers_count: 188000,
    forks_count: 74200,
    watchers_count: 7800,
    open_issues_count: 2400,
    language: 'C++',
    license: {
      key: 'apache-2.0',
      name: 'Apache License 2.0',
      url: 'https://api.github.com/licenses/apache-2.0',
    },
    topics: [
      'deep-learning',
      'deep-neural-networks',
      'distributed',
      'machine-learning',
      'ml',
      'neural-network',
      'python',
      'tensorflow',
    ],
    updated_at: recentDate(0),
    pushed_at: recentDate(0),
    created_at: '2015-11-07T01:19:20Z',
    is_starred: false,
  },
  {
    id: 12888993,
    name: 'gin',
    full_name: 'gin-gonic/gin',
    owner: {
      login: 'gin-gonic',
      avatar_url: 'https://avatars.githubusercontent.com/u/7894478?v=4',
    },
    description: 'Gin is a HTTP web framework written in Go (Golang).',
    html_url: 'https://github.com/gin-gonic/gin',
    stargazers_count: 80500,
    forks_count: 8100,
    watchers_count: 1300,
    open_issues_count: 820,
    language: 'Go',
    license: { key: 'mit', name: 'MIT License', url: 'https://api.github.com/licenses/mit' },
    topics: ['gin', 'go', 'golang', 'http', 'web', 'web-framework'],
    updated_at: recentDate(1),
    pushed_at: recentDate(5),
    created_at: '2014-06-16T23:57:25Z',
    is_starred: false,
  },
];

export const DEMO_SEARCH_RESULTS: Record<string, Repository[]> = {
  react: [
    ...DEMO_STARRED_REPOS.filter((r) =>
      [
        'react',
        'next.js',
        'remix',
        'react-router',
        'redux',
        'zustand',
        'react-hook-form',
        'query',
      ].includes(r.name)
    ),
  ],
  typescript: [
    ...DEMO_STARRED_REPOS.filter(
      (r) => r.language === 'TypeScript' || r.name === 'TypeScript'
    ).slice(0, 12),
  ],
  python: [
    ...DEMO_STARRED_REPOS.filter((r) => r.language === 'Python'),
    ADDITIONAL_SEARCH_REPOS.find((r) => r.name === 'pytorch')!,
    ADDITIONAL_SEARCH_REPOS.find((r) => r.name === 'tensorflow')!,
  ],
  ai: [
    ...DEMO_STARRED_REPOS.filter((r) =>
      r.topics.some((t) => ['ai', 'machine-learning', 'llm', 'deep-learning'].includes(t))
    ),
    ADDITIONAL_SEARCH_REPOS.find((r) => r.name === 'pytorch')!,
    ADDITIONAL_SEARCH_REPOS.find((r) => r.name === 'tensorflow')!,
  ],
  rust: [...DEMO_STARRED_REPOS.filter((r) => r.language === 'Rust')],
};

/**
 * Get demo search results for a query.
 * Returns empty array if no match (matches production behavior).
 */
export function getDemoSearchResults(query: string): Repository[] {
  const lowerQuery = query.toLowerCase().trim();

  if (!lowerQuery) return [];

  for (const [keyword, results] of Object.entries(DEMO_SEARCH_RESULTS)) {
    if (lowerQuery.includes(keyword)) {
      return results;
    }
  }

  // No match - return empty (matches production "no results" behavior)
  return [];
}

/**
 * Get repos for a specific radar by ID.
 */
export function getDemoRadarRepos(radarId: string): Repository[] {
  const repoIds = DEMO_RADAR_REPOS.filter((rr) => rr.radar_id === radarId).map(
    (rr) => rr.github_repo_id
  );

  return DEMO_STARRED_REPOS.filter((repo) => repoIds.includes(repo.id));
}

/**
 * Check if a repo is in a specific radar.
 */
export function isRepoInDemoRadar(radarId: string, repoId: number): boolean {
  return DEMO_RADAR_REPOS.some((rr) => rr.radar_id === radarId && rr.github_repo_id === repoId);
}
